### ISSUE TITLE
move TwoButtonShutter to ophyd

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/ophyd#504]
this logic is replicated across multiple beamlines and should be added to ophyd:

https://github.com/NSLS-II-XFP/profile_collection/blob/master/startup/10-motors.py#L7

@tacaswell mentioned this

**Comment by mrakitin** [comment]
There were [some improvements](https://github.com/NSLS-II-XFP/profile_collection/compare/master@%7B2018-02-07%7D...master@%7B2018-02-10%7D#diff-cabc947caae398568d7cac4fa8328794) implemented recently. Maybe we need to see how it runs during this cycle, and then it can be transferred to ophyd.
