### ISSUE TITLE
Consider replacing `get_prop_name` with `inflection.underscore`

### ISSUE THREAD

**Issue by klauer** [bluesky/ophyd#716]
https://github.com/NSLS-II/ophyd/blob/cf2b85c2479d645c144289fca79f74b151183417/ophyd/areadetector/util.py#L15

https://inflection.readthedocs.io/en/latest/#inflection.underscore

**Comment by mrakitin** [comment]
@klauer, was it resolved by a PR? I only see #401 above...

**Comment by klauer** [comment]
No - I had/have too many issues open that amount to "discussion with myself". 

I'm starting to cull them more frequently as my musings aren't even close to as useful as I'd hope they'd be.
