### ISSUE TITLE
Backport a fix for pyepics context kwarg warning

### ISSUE THREAD

**Issue by danielballan** [bluesky/ophyd#773]
This warning

```
/srv/conda/envs/notebook/lib/python3.7/site-packages/epics/pv.py:110: UserWarning: The `context` kwarg for epics.get_pv() is deprecated. New PVs will _not_ be created in the requested context.
```

mentioned also by @prjemian in #765 should be back-ported to 1.3.x since we still have some work to do before releasing 1.4.0.

**Comment by jklynch** [comment]
The warning seems to be coming from this line

https://github.com/bluesky/ophyd/blob/d2ed9f3c27299eada78c7d1a7f0ff50c6c68157c/ophyd/_pyepics_shim.py#L23
