### ISSUE TITLE
MoveStatus watch method error

### ISSUE THREAD

**Issue by AbbyGi** [bluesky/ophyd#794]
In the MoveStatus _notify_watchers method, if the fraction calculation causes an exception, fraction is set to None and the next if statement causes an error if None is passed into np.isnan.
```py
import numpy as np
a = None
print(np.isnan(a))
```
```py
ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by tacaswell** [comment]
Closed by https://github.com/bluesky/ophyd/pull/795
