### ISSUE TITLE
Backend `add_callback` should not block waiting for connection

### ISSUE THREAD

**Issue by klauer** [bluesky/ophyd#847]
Refactor pyepics, caproto backends to add the requested callbacks on connection

**Comment by danielballan** [comment]
Related to https://github.com/caproto/caproto/issues/539

**Comment by klauer** [comment]
@MikeHart85 just a thought - this may be a good issue to start digging into/understanding `ophyd.signal` internals.

**Comment by MikeHart85** [comment]
I'll have a look, thanks!
