### ISSUE TITLE
Module named 'signal' in ophyd can result in difficult-to-debug issues

### ISSUE THREAD

**Issue by klauer** [bluesky/ophyd#848]
Depending on the current working directory, `ophyd.signal` can be imported instead of the standard library `signal`. 

While renaming would be ideal, a fallback can be implementing something such as:
https://github.com/pcdshub/pcdsdevices/blob/6dd968b5bd323446b8ba13cd5190165df9bbdf16/pcdsdevices/signal.py#L4-L11

xref https://github.com/pcdshub/typhos/issues/275 https://github.com/pcdshub/pcdsdevices/issues/347

**Comment by danielballan** [comment]
I am in favor of adding that fallback.
