### ISSUE TITLE
ENH: ScalerCH.select_channels() arg should be optional

### ISSUE THREAD

**Issue by prjemian** [bluesky/ophyd#870]
In the `ScalerCH.select_channels()` method, it would be more intuitive if the `chan_names` argument were optional.  Make this a kwarg with default value of `None` (to match current handling of `chan_names`).

**Comment by tacaswell** [comment]
:+1: If we didn't already support None -> "all of them" I would have complained that it is not clear if None should mean "all" or "none", but as we already have made that decision....
