### ISSUE TITLE
Support EPICS scaler record .RATE field

### ISSUE THREAD

**Issue by prjemian** [bluesky/ophyd#964]
The EPICS scaler record has a [`.RATE` field](https://github.com/epics-modules/scaler/blob/master/scalerApp/src/scalerRecord.dbd#L74-L79) that controls the rate at which CA monitors will be posted while the scaler is acquiring.

```
	field(RATE,DBF_FLOAT) {
		prompt("Display Rate (Hz.)")
		promptgroup(GUI_COMMON)
		special(SPC_MOD)
		initial("10")
	}
```

Make sure the scaler support in ophyd provides a signal for this field.

**Comment by prjemian** [comment]
### `EpicsScaler`
https://github.com/bluesky/ophyd/blob/03585f0b02752d5975da393a889e5c5cecd06fd7/ophyd/scaler.py#L51

### `ScalerCH`
https://github.com/bluesky/ophyd/blob/03585f0b02752d5975da393a889e5c5cecd06fd7/ophyd/scaler.py#L114

**Comment by prjemian** [comment]
Nothing to do except apply consistency to the `kind` attribute.  Prefer to use `Kind.omitted` since this is cosmetic while the scaler is acquiring and does not affect any data to be stored.

Opinions?

* [ ] leave it as-is
* [ ] change `EpicsScaler`
* [ ] change `ScalerCH`
* [ ] other

**Comment by danielballan** [comment]
Can we imagine a situation where it might be nice to be able to lookup the intended RATE? Maybe to check it against the actual RATE or filter Runs in a search by those than have a RATE greater than some value?

I lean toward "config" because those scenarios don't sound _too_ out there to me. But perhaps those examples are too contrived and we should just move to "omitted". I would be happy either way, and I agree that consistency is the priority here.

**Comment by prjemian** [comment]
>Can we imagine a situation where it might be nice to be able to lookup the intended RATE? 

Not a likely scenario.  This field is usually set _once every few years_, if that often.  That's why `omitted` v. `config`.  So, why make it into an ophyd signal at all?  One instrument asked for it.

**Comment by prjemian** [comment]
This is the screen that shows the field (in the red box):
![Clipboard03](https://user-images.githubusercontent.com/2279984/108538068-ffb1a500-72a3-11eb-81ca-0af1c73db0c4.png)

**Comment by prjemian** [comment]
Proceeding with PR that makes `Kind.omitted` the consistent choice.

**Comment by prjemian** [comment]
Note: attribute `auto_count_update_rate` also affected by these same comments.
