### ISSUE TITLE
SignalRO not imported by ophyd/__init__.py

### ISSUE THREAD

**Issue by pshafer-als** [bluesky/ophyd#990]
To use `SignalRO`, it must be imported from its submodule, rather than the main `ophyd` module.

```python
from ophyd.signal import SignalRO  # This works
from ophyd import SignalRO  # This does NOT work
```

Could `SignalRO` be imported in '[ophyd/__init__py](https://github.com/bluesky/ophyd/blob/master/ophyd/__init__.py#L78)' just like (`Signal`, `EpicsSignal`, `EpicsSignalRO`, `DerivedSignal`) and many other ophyd classes?  Or is `SignalRO` obscured, and intended only for edge cases?

'[ophyd/__init__py](https://github.com/bluesky/ophyd/blob/master/ophyd/__init__.py#L78)':
```python
[line 78] from .signal import (Signal, EpicsSignal, EpicsSignalRO, DerivedSignal)  # Replace this line...
[line 78] from .signal import (Signal, SignalRO, EpicsSignal, EpicsSignalRO, DerivedSignal)  # ...with this line
```

**Comment by mrakitin** [comment]
@pshafer-als, thanks for the suggestion. I don't see any issue with it being available from the top-level import. A PR is always welcome.

**Comment by pshafer-als** [comment]
Thanks for confirming.  I’ll submit a PR then.

-Padraic
